<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="4" failed="2" ignored="0" total="8" passed="2">
  <reporter-output>
    <line>
      <![CDATA[Retrying test b with status FAILURE for the 1 time(s).]]>
    </line>
    <line>
      <![CDATA[Retrying test b with status FAILURE for the 2 time(s).]]>
    </line>
    <line>
      <![CDATA[Retrying test c with status FAILURE for the 1 time(s).]]>
    </line>
    <line>
      <![CDATA[Retrying test c with status FAILURE for the 2 time(s).]]>
    </line>
  </reporter-output>
  <suite name="Insurence QA Automation" duration-ms="77407" started-at="2019-12-11T07:36:26Z" finished-at="2019-12-11T07:37:43Z">
    <groups>
    </groups>
    <test name="Insurence QA" duration-ms="77407" started-at="2019-12-11T07:36:26Z" finished-at="2019-12-11T07:37:43Z">
      <class name="com.Base.BaseTest">
        <test-method status="PASS" signature="listners()[pri:0, instance:com.Base.BaseTest@cb644e]" name="listners" is-config="true" duration-ms="201" started-at="2019-12-11T07:36:26Z" finished-at="2019-12-11T07:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- listners -->
        <test-method status="PASS" signature="initlization_SetUp(org.testng.ITestResult)[pri:0, instance:com.Base.BaseTest@cb644e]" name="initlization_SetUp" is-config="true" duration-ms="9442" started-at="2019-12-11T07:36:26Z" finished-at="2019-12-11T07:36:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=a status=SUCCESS method=BaseTest.a()[pri:0, instance:com.Base.BaseTest@cb644e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initlization_SetUp -->
        <test-method status="PASS" signature="a()[pri:0, instance:com.Base.BaseTest@cb644e]" name="a" duration-ms="8" started-at="2019-12-11T07:36:36Z" finished-at="2019-12-11T07:36:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- a -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.Base.BaseTest@cb644e]" name="tearDown" is-config="true" duration-ms="762" started-at="2019-12-11T07:36:36Z" finished-at="2019-12-11T07:36:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=a status=SUCCESS method=BaseTest.a()[pri:0, instance:com.Base.BaseTest@cb644e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="initlization_SetUp(org.testng.ITestResult)[pri:0, instance:com.Base.BaseTest@cb644e]" name="initlization_SetUp" is-config="true" duration-ms="8622" started-at="2019-12-11T07:36:36Z" finished-at="2019-12-11T07:36:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=b status=SKIP method=BaseTest.b()[pri:0, instance:com.Base.BaseTest@cb644e] output=Retrying test b with status FAILURE for the 1 time(s).]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initlization_SetUp -->
        <test-method status="SKIP" signature="b()[pri:0, instance:com.Base.BaseTest@cb644e]" name="b" duration-ms="2" started-at="2019-12-11T07:36:45Z" finished-at="2019-12-11T07:36:45Z">
          <exception class="java.lang.ArithmeticException">
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException
at com.Base.BaseTest.b(BaseTest.java:263)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
            <line>
              <![CDATA[Retrying test b with status FAILURE for the 1 time(s).]]>
            </line>
          </reporter-output>
        </test-method> <!-- b -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.Base.BaseTest@cb644e]" name="tearDown" is-config="true" duration-ms="1170" started-at="2019-12-11T07:36:45Z" finished-at="2019-12-11T07:36:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=b status=SKIP method=BaseTest.b()[pri:0, instance:com.Base.BaseTest@cb644e] output=Retrying test b with status FAILURE for the 1 time(s).]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="initlization_SetUp(org.testng.ITestResult)[pri:0, instance:com.Base.BaseTest@cb644e]" name="initlization_SetUp" is-config="true" duration-ms="9470" started-at="2019-12-11T07:36:46Z" finished-at="2019-12-11T07:36:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=b status=SKIP method=BaseTest.b()[pri:0, instance:com.Base.BaseTest@cb644e] output=Retrying test b with status FAILURE for the 2 time(s).]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initlization_SetUp -->
        <test-method status="SKIP" signature="b()[pri:0, instance:com.Base.BaseTest@cb644e]" name="b" duration-ms="2" started-at="2019-12-11T07:36:56Z" finished-at="2019-12-11T07:36:56Z">
          <exception class="java.lang.ArithmeticException">
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException
at com.Base.BaseTest.b(BaseTest.java:263)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
            <line>
              <![CDATA[Retrying test b with status FAILURE for the 2 time(s).]]>
            </line>
          </reporter-output>
        </test-method> <!-- b -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.Base.BaseTest@cb644e]" name="tearDown" is-config="true" duration-ms="783" started-at="2019-12-11T07:36:56Z" finished-at="2019-12-11T07:36:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=b status=SKIP method=BaseTest.b()[pri:0, instance:com.Base.BaseTest@cb644e] output=Retrying test b with status FAILURE for the 2 time(s).]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="initlization_SetUp(org.testng.ITestResult)[pri:0, instance:com.Base.BaseTest@cb644e]" name="initlization_SetUp" is-config="true" duration-ms="8120" started-at="2019-12-11T07:36:56Z" finished-at="2019-12-11T07:37:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=b status=FAILURE method=BaseTest.b()[pri:0, instance:com.Base.BaseTest@cb644e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initlization_SetUp -->
        <test-method status="FAIL" signature="b()[pri:0, instance:com.Base.BaseTest@cb644e]" name="b" duration-ms="2" started-at="2019-12-11T07:37:04Z" finished-at="2019-12-11T07:37:04Z">
          <exception class="java.lang.ArithmeticException">
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException
at com.Base.BaseTest.b(BaseTest.java:263)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- b -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.Base.BaseTest@cb644e]" name="tearDown" is-config="true" duration-ms="1236" started-at="2019-12-11T07:37:05Z" finished-at="2019-12-11T07:37:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=b status=FAILURE method=BaseTest.b()[pri:0, instance:com.Base.BaseTest@cb644e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="initlization_SetUp(org.testng.ITestResult)[pri:0, instance:com.Base.BaseTest@cb644e]" name="initlization_SetUp" is-config="true" duration-ms="8365" started-at="2019-12-11T07:37:06Z" finished-at="2019-12-11T07:37:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=c status=SKIP method=BaseTest.c()[pri:0, instance:com.Base.BaseTest@cb644e] output=Retrying test c with status FAILURE for the 1 time(s).]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initlization_SetUp -->
        <test-method status="SKIP" signature="c()[pri:0, instance:com.Base.BaseTest@cb644e]" name="c" duration-ms="2" started-at="2019-12-11T07:37:14Z" finished-at="2019-12-11T07:37:14Z">
          <exception class="java.lang.ArithmeticException">
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException
at com.Base.BaseTest.c(BaseTest.java:268)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
            <line>
              <![CDATA[Retrying test c with status FAILURE for the 1 time(s).]]>
            </line>
          </reporter-output>
        </test-method> <!-- c -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.Base.BaseTest@cb644e]" name="tearDown" is-config="true" duration-ms="759" started-at="2019-12-11T07:37:14Z" finished-at="2019-12-11T07:37:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=c status=SKIP method=BaseTest.c()[pri:0, instance:com.Base.BaseTest@cb644e] output=Retrying test c with status FAILURE for the 1 time(s).]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="initlization_SetUp(org.testng.ITestResult)[pri:0, instance:com.Base.BaseTest@cb644e]" name="initlization_SetUp" is-config="true" duration-ms="8299" started-at="2019-12-11T07:37:15Z" finished-at="2019-12-11T07:37:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=c status=SKIP method=BaseTest.c()[pri:0, instance:com.Base.BaseTest@cb644e] output=Retrying test c with status FAILURE for the 2 time(s).]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initlization_SetUp -->
        <test-method status="SKIP" signature="c()[pri:0, instance:com.Base.BaseTest@cb644e]" name="c" duration-ms="2" started-at="2019-12-11T07:37:23Z" finished-at="2019-12-11T07:37:23Z">
          <exception class="java.lang.ArithmeticException">
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException
at com.Base.BaseTest.c(BaseTest.java:268)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
            <line>
              <![CDATA[Retrying test c with status FAILURE for the 2 time(s).]]>
            </line>
          </reporter-output>
        </test-method> <!-- c -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.Base.BaseTest@cb644e]" name="tearDown" is-config="true" duration-ms="756" started-at="2019-12-11T07:37:23Z" finished-at="2019-12-11T07:37:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=c status=SKIP method=BaseTest.c()[pri:0, instance:com.Base.BaseTest@cb644e] output=Retrying test c with status FAILURE for the 2 time(s).]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="initlization_SetUp(org.testng.ITestResult)[pri:0, instance:com.Base.BaseTest@cb644e]" name="initlization_SetUp" is-config="true" duration-ms="8413" started-at="2019-12-11T07:37:24Z" finished-at="2019-12-11T07:37:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=c status=FAILURE method=BaseTest.c()[pri:0, instance:com.Base.BaseTest@cb644e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initlization_SetUp -->
        <test-method status="FAIL" signature="c()[pri:0, instance:com.Base.BaseTest@cb644e]" name="c" duration-ms="1" started-at="2019-12-11T07:37:32Z" finished-at="2019-12-11T07:37:32Z">
          <exception class="java.lang.ArithmeticException">
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException
at com.Base.BaseTest.c(BaseTest.java:268)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- c -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.Base.BaseTest@cb644e]" name="tearDown" is-config="true" duration-ms="1421" started-at="2019-12-11T07:37:32Z" finished-at="2019-12-11T07:37:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=c status=FAILURE method=BaseTest.c()[pri:0, instance:com.Base.BaseTest@cb644e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="initlization_SetUp(org.testng.ITestResult)[pri:0, instance:com.Base.BaseTest@cb644e]" name="initlization_SetUp" is-config="true" duration-ms="8170" started-at="2019-12-11T07:37:34Z" finished-at="2019-12-11T07:37:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=d status=SUCCESS method=BaseTest.d()[pri:0, instance:com.Base.BaseTest@cb644e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initlization_SetUp -->
        <test-method status="PASS" signature="d()[pri:0, instance:com.Base.BaseTest@cb644e]" name="d" duration-ms="2" started-at="2019-12-11T07:37:42Z" finished-at="2019-12-11T07:37:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- d -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.Base.BaseTest@cb644e]" name="tearDown" is-config="true" duration-ms="760" started-at="2019-12-11T07:37:42Z" finished-at="2019-12-11T07:37:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=d status=SUCCESS method=BaseTest.d()[pri:0, instance:com.Base.BaseTest@cb644e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="endListners()[pri:0, instance:com.Base.BaseTest@cb644e]" name="endListners" is-config="true" duration-ms="580" started-at="2019-12-11T07:37:43Z" finished-at="2019-12-11T07:37:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endListners -->
      </class> <!-- com.Base.BaseTest -->
    </test> <!-- Insurence QA -->
  </suite> <!-- Insurence QA Automation -->
</testng-results>
